# CloudBees Unify Deployer Workflow
# Orchestrates deployment of banking-app component to target environment

apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deployer

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Target environment (qa/staging/prod)
      manifest:
        type: string
        required: true
        description: Release manifest (JSON)
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
        description: Target environment (qa/staging/prod)
        default: qa
      manifest:
        type: string
        required: true
        description: Release manifest (JSON)

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: read

jobs:
  banking-app:
    if: ${{ fromJSON(inputs.manifest)['banking-app'].deploy }}
    uses: tdesai2705/banking-app/.cloudbees/workflows/deploy.yaml@9c293f0
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['banking-app'].id }}
      artifact-url: ${{ fromJSON(inputs.manifest)['banking-app'].url }}
      environment: ${{ inputs.environment }}
    secrets: inherit
